// <auto-generated />
using System;
using CourseSignupSystemServer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CourseSignupSystemServer.Migrations
{
    [DbContext(typeof(ApiDbContext))]
    [Migration("20230726193807_UpdateChucVu")]
    partial class UpdateChucVu
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CourseSignupSystemServer.Models.BoMon", b =>
                {
                    b.Property<string>("MaBM")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TenBM")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("MaBM");

                    b.ToTable("BoMon");
                });

            modelBuilder.Entity("CourseSignupSystemServer.Models.ChucVu", b =>
                {
                    b.Property<string>("MaCV")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MoTa")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TenCV")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("nvarchar(75)");

                    b.HasKey("MaCV");

                    b.ToTable("ChucVu");
                });

            modelBuilder.Entity("CourseSignupSystemServer.Models.DangKy", b =>
                {
                    b.Property<string>("MaLop")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaHV")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("NgayDK")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayThuHP")
                        .HasColumnType("datetime2");

                    b.Property<bool>("ThuHocPhi")
                        .HasColumnType("bit");

                    b.HasKey("MaLop", "MaHV");

                    b.HasIndex("MaHV");

                    b.ToTable("DangKy");
                });

            modelBuilder.Entity("CourseSignupSystemServer.Models.Diem", b =>
                {
                    b.Property<string>("MaMH")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaHV")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaLDiem")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("SoDiem")
                        .HasColumnType("float");

                    b.HasKey("MaMH", "MaHV", "MaLDiem");

                    b.HasIndex("MaHV");

                    b.HasIndex("MaLDiem");

                    b.ToTable("Diem");
                });

            modelBuilder.Entity("CourseSignupSystemServer.Models.DoanhThu", b =>
                {
                    b.Property<string>("MaDoanhThu")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ThoiGian")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<double>("TongTien")
                        .HasColumnType("float");

                    b.HasKey("MaDoanhThu");

                    b.ToTable("DoanhThu");
                });

            modelBuilder.Entity("CourseSignupSystemServer.Models.GiangVien", b =>
                {
                    b.Property<string>("MaGV")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CMND")
                        .HasColumnType("int");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("GioiTinh")
                        .HasColumnType("bit");

                    b.Property<string>("HinhDaiDien")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaBM")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaLuong")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("NgayHopTac")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SDT")
                        .HasMaxLength(10)
                        .HasColumnType("int");

                    b.Property<string>("TenGV")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("TrangThaiHD")
                        .HasColumnType("bit");

                    b.HasKey("MaGV");

                    b.HasIndex("MaBM");

                    b.HasIndex("MaLuong");

                    b.ToTable("GiangVien");
                });

            modelBuilder.Entity("CourseSignupSystemServer.Models.HocVien", b =>
                {
                    b.Property<string>("MaHV")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AnhDaiDien")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhuHuynh")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SDTLienLac")
                        .HasMaxLength(10)
                        .HasColumnType("int");

                    b.Property<string>("TenHV")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaHV");

                    b.ToTable("HocVien");
                });

            modelBuilder.Entity("CourseSignupSystemServer.Models.Khoa", b =>
                {
                    b.Property<string>("MaKhoa")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaNienKhoa")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TenKhoa")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.HasKey("MaKhoa");

                    b.HasIndex("MaNienKhoa");

                    b.ToTable("Khoa");
                });

            modelBuilder.Entity("CourseSignupSystemServer.Models.LichNghi", b =>
                {
                    b.Property<string>("MaLN")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayBD")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayKT")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenLN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaLN");

                    b.ToTable("LichNghi");
                });

            modelBuilder.Entity("CourseSignupSystemServer.Models.LichVang", b =>
                {
                    b.Property<string>("MaLop")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaHV")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LyDo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayVang")
                        .HasColumnType("datetime2");

                    b.HasKey("MaLop", "MaHV");

                    b.HasIndex("MaHV");

                    b.ToTable("LichVang");
                });

            modelBuilder.Entity("CourseSignupSystemServer.Models.LienHe", b =>
                {
                    b.Property<string>("MaLH")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaHV")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("NgayLH")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaLH");

                    b.HasIndex("MaHV");

                    b.ToTable("LienHe");
                });

            modelBuilder.Entity("CourseSignupSystemServer.Models.LoaiDiem", b =>
                {
                    b.Property<string>("MaLDiem")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("HeSo")
                        .HasColumnType("float");

                    b.Property<string>("TenLDiem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaLDiem");

                    b.ToTable("LoaiDiem");
                });

            modelBuilder.Entity("CourseSignupSystemServer.Models.LopHoc", b =>
                {
                    b.Property<string>("MaLop")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("HocPhi")
                        .HasColumnType("float");

                    b.Property<string>("MaDT")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaGV")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaKhoa")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaLichNghi")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaMH")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("NgayKhaiGiang")
                        .HasColumnType("datetime2");

                    b.Property<string>("Phong")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SoBuoiHoc")
                        .HasColumnType("int");

                    b.Property<string>("TenLop")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThoiGianHoc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("MaLop");

                    b.HasIndex("MaDT");

                    b.HasIndex("MaGV");

                    b.HasIndex("MaKhoa");

                    b.HasIndex("MaLichNghi");

                    b.HasIndex("MaMH");

                    b.ToTable("LopHoc");
                });

            modelBuilder.Entity("CourseSignupSystemServer.Models.Luong", b =>
                {
                    b.Property<string>("MaLuong")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("NgayNhan")
                        .HasColumnType("datetime2");

                    b.Property<double>("PhuCap")
                        .HasColumnType("float");

                    b.Property<double>("ThucLanh")
                        .HasColumnType("float");

                    b.Property<double>("TienThuong")
                        .HasColumnType("float");

                    b.HasKey("MaLuong");

                    b.ToTable("Luong");
                });

            modelBuilder.Entity("CourseSignupSystemServer.Models.MonHoc", b =>
                {
                    b.Property<string>("MaMH")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaBM")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TenMH")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.HasKey("MaMH");

                    b.HasIndex("MaBM");

                    b.ToTable("MonHoc");
                });

            modelBuilder.Entity("CourseSignupSystemServer.Models.NhanVien", b =>
                {
                    b.Property<string>("MaNV")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CMND")
                        .HasColumnType("int");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("GioiTinh")
                        .HasColumnType("bit");

                    b.Property<string>("HinhDaiDien")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaCV")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaLuong")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayVaoLam")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SDT")
                        .HasMaxLength(10)
                        .HasColumnType("int");

                    b.Property<string>("TenNV")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("TrangThaiHD")
                        .HasColumnType("bit");

                    b.HasKey("MaNV");

                    b.HasIndex("MaCV");

                    b.HasIndex("MaLuong");

                    b.ToTable("NhanVien");
                });

            modelBuilder.Entity("CourseSignupSystemServer.Models.NienKhoa", b =>
                {
                    b.Property<string>("MaNK")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TenNK")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ThoiGian")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.HasKey("MaNK");

                    b.ToTable("NienKhoa");
                });

            modelBuilder.Entity("CourseSignupSystemServer.Models.DangKy", b =>
                {
                    b.HasOne("CourseSignupSystemServer.Models.HocVien", "HocViens")
                        .WithMany()
                        .HasForeignKey("MaHV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CourseSignupSystemServer.Models.LopHoc", "Lops")
                        .WithMany()
                        .HasForeignKey("MaLop")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HocViens");

                    b.Navigation("Lops");
                });

            modelBuilder.Entity("CourseSignupSystemServer.Models.Diem", b =>
                {
                    b.HasOne("CourseSignupSystemServer.Models.HocVien", "HocViens")
                        .WithMany()
                        .HasForeignKey("MaHV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CourseSignupSystemServer.Models.LoaiDiem", "LoaiDiems")
                        .WithMany()
                        .HasForeignKey("MaLDiem")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CourseSignupSystemServer.Models.MonHoc", "MonHocs")
                        .WithMany()
                        .HasForeignKey("MaMH")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HocViens");

                    b.Navigation("LoaiDiems");

                    b.Navigation("MonHocs");
                });

            modelBuilder.Entity("CourseSignupSystemServer.Models.GiangVien", b =>
                {
                    b.HasOne("CourseSignupSystemServer.Models.BoMon", "BoMons")
                        .WithMany()
                        .HasForeignKey("MaBM")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CourseSignupSystemServer.Models.Luong", "Luongs")
                        .WithMany()
                        .HasForeignKey("MaLuong")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BoMons");

                    b.Navigation("Luongs");
                });

            modelBuilder.Entity("CourseSignupSystemServer.Models.Khoa", b =>
                {
                    b.HasOne("CourseSignupSystemServer.Models.NienKhoa", "NienKhoas")
                        .WithMany()
                        .HasForeignKey("MaNienKhoa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NienKhoas");
                });

            modelBuilder.Entity("CourseSignupSystemServer.Models.LichVang", b =>
                {
                    b.HasOne("CourseSignupSystemServer.Models.HocVien", "HocViens")
                        .WithMany()
                        .HasForeignKey("MaHV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CourseSignupSystemServer.Models.LopHoc", "Lops")
                        .WithMany()
                        .HasForeignKey("MaLop")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HocViens");

                    b.Navigation("Lops");
                });

            modelBuilder.Entity("CourseSignupSystemServer.Models.LienHe", b =>
                {
                    b.HasOne("CourseSignupSystemServer.Models.HocVien", "HocViens")
                        .WithMany()
                        .HasForeignKey("MaHV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HocViens");
                });

            modelBuilder.Entity("CourseSignupSystemServer.Models.LopHoc", b =>
                {
                    b.HasOne("CourseSignupSystemServer.Models.DoanhThu", "DoanhThus")
                        .WithMany()
                        .HasForeignKey("MaDT")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CourseSignupSystemServer.Models.GiangVien", "GiangViens")
                        .WithMany()
                        .HasForeignKey("MaGV")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CourseSignupSystemServer.Models.Khoa", "Khoas")
                        .WithMany()
                        .HasForeignKey("MaKhoa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CourseSignupSystemServer.Models.LichNghi", "LichNghis")
                        .WithMany()
                        .HasForeignKey("MaLichNghi")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CourseSignupSystemServer.Models.MonHoc", "MonHocs")
                        .WithMany()
                        .HasForeignKey("MaMH")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DoanhThus");

                    b.Navigation("GiangViens");

                    b.Navigation("Khoas");

                    b.Navigation("LichNghis");

                    b.Navigation("MonHocs");
                });

            modelBuilder.Entity("CourseSignupSystemServer.Models.MonHoc", b =>
                {
                    b.HasOne("CourseSignupSystemServer.Models.BoMon", "BoMons")
                        .WithMany()
                        .HasForeignKey("MaBM")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BoMons");
                });

            modelBuilder.Entity("CourseSignupSystemServer.Models.NhanVien", b =>
                {
                    b.HasOne("CourseSignupSystemServer.Models.ChucVu", "ChucVus")
                        .WithMany()
                        .HasForeignKey("MaCV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CourseSignupSystemServer.Models.Luong", "Luongs")
                        .WithMany()
                        .HasForeignKey("MaLuong")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChucVus");

                    b.Navigation("Luongs");
                });
#pragma warning restore 612, 618
        }
    }
}
