// <auto-generated />
using CourseSignupSystemServer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CourseSignupSystemServer.Migrations
{
    [DbContext(typeof(ApiDbContext))]
    [Migration("20230724090925_AddTableChucVu")]
    partial class AddTableChucVu
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CourseSignupSystemServer.Models.ChucVu", b =>
                {
                    b.Property<string>("MaCV")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TenCV")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaCV");

                    b.ToTable("ChucVu");
                });
#pragma warning restore 612, 618
        }
    }
}
